# Generated by Django 2.2 on 2022-11-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_taskmate_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmate',
            old_name='manager',
            new_name='manage',
        ),
    ]
